### ISSUE TITLE
Deployment of the webpage

### ISSUE THREAD

**Issue by tusharnankani** [captain-aman-11/Calculator-made-with-JS#1]
Hi @Lord-Aman! 

Very neatly done! Good work! 🤗

I would recommend you to deploy the webpage. You can use a lot of free services like GitHub pages or Netlify.
It will helpful for others to look at your project without having to download the whole setup.

All the best,
Tushar Nankani

**Comment by tusharnankani** [comment]
Hi! 

I just saw the webpage is already deployed to gh-pages. My bad! 

- You can add the link in the about section of the repository! ^_^

Thanks,
Tushar Nankani

**Comment by captain-aman-11** [comment]
Thanks @tusharnankani for your concern and consideration. I'll definitely update the link in the about section.
